apiVersion: v1
kind: Service
metadata:
  name: ekart-service
spec:
  type: NodePort
  selector:
    app: ekart
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
